### ISSUE TITLE
Master-1 node not ok

### ISSUE THREAD

**Issue by oguzhalit** [Kubeinit/kubeinit#11]
what is wrong ?

![Screenshot from 2020-08-31 18-02-23](https://user-images.githubusercontent.com/37263350/91734915-3a1f6c80-ebb4-11ea-9820-67fcefb810dc.png)
![Screenshot from 2020-08-31 18-01-42](https://user-images.githubusercontent.com/37263350/91734921-3b509980-ebb4-11ea-9195-711458b0021d.png)
![Screenshot from 2020-08-31 18-00-16](https://user-images.githubusercontent.com/37263350/91734922-3b509980-ebb4-11ea-84f5-51c302efdbde.png)
![Screenshot from 2020-08-31 18-00-08](https://user-images.githubusercontent.com/37263350/91734925-3be93000-ebb4-11ea-9b8f-99428e067e34.png)

**Comment by sonicwilson** [comment]
this is the same error ive been getting also. I havent been able to figure it out. if you do -vvv it give a little more info but not enough

**Comment by oguzhalit** [comment]
restart playbook and resolve but i dont unterstand 
why did this happen?
![Screenshot from 2020-08-31 18-24-22](https://user-images.githubusercontent.com/37263350/91737099-4a851680-ebb7-11ea-83e2-e84af0b9a9f6.png)

**Comment by ccamacho** [comment]
Hi @oguzhalit 
Thanks for raising an issue, please if you feel this project is useful to you consider starring this repository to keep in touch.
---
@sonicwilson also reported this, and the thing is that I'm a bit puzzled because I wasn't able to reproduce it yet.

From your latest print screen (You should have 3 master nodes ready and not  2)

Skip the Ansible output and this might be some internal to the cluster (Ansible just hangs)

Let's try to get into the nodes and do some debugging.

From the hypervisor can you run:

virsh console okd-master-01
    - This would give you the master-01 console to see if there is something wrong when the cluster is provisioned (this node in particular). Try to run the deployment command and from the moment the master nodes are created, connect, and if there is an issue provisioning the node (i.e. DNS) it should pop up, but the output is massive so you need to check it in realtime otherwise it will disappear in a sea of letters...

ssh root@10.0.0.100
    - This would give you access to the service node, from there:
       * Check if the bind, haproxy, and apache service is up (they should)
       * ping google, and try to resolve any DNS name (this machine should have full Internet access)
       * ping 10.0.0.1, 10.0.0.2, 10.0.03 (the master nodes)
       * export KUBECONFIG=~/install_dir/auth/kubeconfig   then run a kubectl get nodes to see the cluster state

Try the latest code as I added some requirements and disk space validations, also, do you have enough RAM?

@sonicwilson maybe you can try to run these commands to see if we can get to the root cause of your issue.

**Comment by ccamacho** [comment]
@sonicwilson @oguzhalit I added also a RAM validation right now, I think it might be related.

**Comment by oguzhalit** [comment]
Thank you, Solved
![Screenshot from 2020-09-01 15-39-05](https://user-images.githubusercontent.com/37263350/91852371-6a751280-ec69-11ea-86c2-735fa7c79aca.png)
