### ISSUE TITLE
Add all nodes to /etc/hosts

### ISSUE THREAD

**Issue by nadenf** [Kubeinit/kubeinit#332]
In addition to adding the hypervisor it would be nice to see all the nodes added to /etc/hosts e.g.

```
eks-master 10.0.0.1
eks-worker 10.0.0.6
```

This would allow you to easily SSH into the right host without consulting the inventory.

**Comment by ccamacho** [comment]
I'm not sure if we want to do this because the guest's names might change after every deployment, and this additional configuration will depend on the inventory file you will use. This means that when you deploy, you don't know what to clean in order to have a consistent hosts file.

The names of the guests must follow a regular expression, maybe we can clean the hosts file based on this regex, and update the content on every run.

@gmarcy do you think it makes sense?

another approach can be to use bind zone as we have all the names information configured there.
